vector <pair <vector<string>, TH1DModel>> h1recOnlyKIT = {
  {{"trPt", "pionneg_kit"},          {"", "", nBinsP, 0, ptMax}},
  {{"trPt", "pionpos_kit"},          {"", "", nBinsP, 0, ptMax}},
  {{"trPt", "proton_kit"},           {"", "", nBinsP, 0, ptMax}},
  {{"trEta", "pionneg_kit"},          {"", "", nBinsEta, 0, etaMax}},
  {{"trEta", "pionpos_kit"},          {"", "", nBinsEta, 0, etaMax}},
  {{"trEta", "proton_kit"},           {"", "", nBinsEta, 0, etaMax}},
  {{"trPhi", "pionneg_kit"},          {"", "", nBinsPhi, -3.15, 3.15}},
  {{"trPhi", "pionpos_kit"},          {"", "", nBinsPhi, -3.15, 3.15}},
  {{"trPhi", "proton_kit"},           {"", "", nBinsPhi, -3.15, 3.15}},
  {{"trY", "pionneg_kit"},          {"", "", nBinsY, yMin, yMax}},
  {{"trY", "pionpos_kit"},          {"", "", nBinsY, yMin, yMax}},
  {{"trY", "proton_kit"},           {"", "", nBinsY, yMin, yMax}},
};

vector <pair <vector<string>, TH2DModel>> h2recOnlyKIT = {
  {{"trPhi", "trPt", "pionneg_kit"},           {"", "", nBinsPhi, -3.15, 3.15, nBinsP, 0, ptMax}},
  {{"trPhi", "trPt", "pionpos_kit"},          {"", "", nBinsPhi, -3.15, 3.15, nBinsP, 0, ptMax}},
  {{"trPhi", "trPt", "proton_kit"},           {"", "", nBinsPhi, -3.15, 3.15, nBinsP, 0, ptMax}},
  {{"trY", "trPt", "pionneg_kit"},        {"", "", nBinsY, yMin, yMax, nBinsP, 0, ptMax}},
  {{"trY", "trPt", "pionpos_kit"},        {"", "", nBinsY, yMin, yMax, nBinsP, 0, ptMax}},
  {{"trY", "trPt", "proton_kit"},         {"", "", nBinsY, yMin, yMax, nBinsP, 0, ptMax}},
  {{"trPhi", "trY", "pionneg_kit"},           {"", "", nBinsPhi, -3.15, 3.15, nBinsY, yMin, yMax}},
  {{"trPhi", "trY", "pionpos_kit"},           {"", "", nBinsPhi, -3.15, 3.15, nBinsY, yMin, yMax}},
  {{"trPhi", "trY", "proton_kit"},            {"", "", nBinsPhi, -3.15, 3.15, nBinsY, yMin, yMax}},
  {{"trLog20p", "trdEdx", "deuteron_kit"},    {"", "", 200, 0, 10, int(nBinsdEdx*2.5), 0, dEdxMax*2.5}},
  {{"trLog20p", "trdEdx", "proton_kit"},      {"", "", 200, 0, 10, int(nBinsdEdx*2.5), 0, dEdxMax*2.5}},
  {{"trLog20p", "trdEdx", "pionpos_kit"},     {"", "", 200, 0, 10, nBinsdEdx, 0, dEdxMax}},
  {{"trLog20p", "trdEdx", "kaonpos_kit"},     {"", "", 200, 0, 10, nBinsdEdx, 0, dEdxMax}},
  {{"trLog20p", "trdEdx", "epos_kit"},        {"", "", 200, 0, 10, nBinsdEdx, 0, dEdxMax}},
  {{"trLog20p", "trdEdx", "pionneg_kit"},     {"", "", 200, 0, 10, nBinsdEdx, 0, dEdxMax}},
  {{"trLog20p", "trdEdx", "kaonneg_kit"},     {"", "", 200, 0, 10, nBinsdEdx, 0, dEdxMax}},
  {{"trLog20p", "trdEdx", "eneg_kit"},        {"", "", 200, 0, 10, nBinsdEdx, 0, dEdxMax}},
  {{"trLog10p", "trPt", "deuteron_kit"},    {"", "", 100, log10(0.05), log10(150), 100, 0, 5}},
  {{"trP", "trPt", "proton_kit"},      {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trP", "trPt", "pionpos_kit"},     {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trP", "trPt", "kaonpos_kit"},     {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trP", "trPt", "epos_kit"},        {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trP", "trPt", "pionneg_kit"},     {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trP", "trPt", "kaonneg_kit"},     {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trP", "trPt", "eneg_kit"},        {"", "", 900, 0.05, 150, 100, 0, 5}},
  {{"trdEdx", "trTofM2", "deuteron_kit"},     {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "proton_kit"},       {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "pionpos_kit"},      {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "kaonpos_kit"},      {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "epos_kit"},         {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "pionneg_kit"},      {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "kaonneg_kit"},      {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
  {{"trdEdx", "trTofM2", "eneg_kit"},         {"", "", nBinsdEdx, 0, dEdxMax, nBinsM2, M2Min, M2Max}},
};
