#include "qaUtils.h"
#include "makeDF.h"

void qa(const char* in="tree.root", const char* out="qa.root", string eventSelection="") {
  RDataFrame d("t", in);
  TFile outFile(out, "recreate");
  auto dd=makeDataFrame(d, &outFile);
  if (eventSelection.size()>0)
    dd=dd.Filter(eventSelection);
  cout << "Number of selected events: " << *(dd.Count()) << endl;

  int nBinsPt=200, nBinsEta=200, nBinsY=300, nBinsPhi=200, Mmax=500, nBinsVtx=500;
  float ptMax=5, etaMax=7, yMin=-1, yMax=3, psdEmax=8000, vtxMax=2;
  vector <pair <vector<string>, TH1DModel>> h1Models = {
    {{"adcV1", ""},                 {"", "", 1000, 0, 1000}},
    {{"adcV1p", ""},                {"", "", 100, 0, 100}},
    {{"adcPSD", ""},                {"", "", 1400, 0, 1400}},
    {{"timesS1_1", ""},             {"", "", int(6e4), -3e4, 3e4}},
    {{"goodS1S2", ""},              {"", "", 2, 0, 2}},
    {{"goodWfa", ""},               {"", "", 2, 0, 2}},
    {{"goodEventBeforeVtxCut", ""}, {"", "", 2, 0, 2}},
    {{"goodVtxZ", ""},              {"", "", 2, 0, 2}},
    {{"goodVtxXY", ""},             {"", "", 2, 0, 2}},
    {{"goodVtxXYwrtBpd3", ""},      {"", "", 2, 0, 2}},
    {{"goodVtxPos", ""},            {"", "", 2, 0, 2}},
    {{"vtxFitPerfect", ""},         {"", "", 2, 0, 2}},
    {{"goodEvent", ""},             {"", "", 2, 0, 2}},
    {{"goodEventOld", ""},          {"", "", 2, 0, 2}},
    {{"Mgood", ""},                 {"", "", Mmax, 0, double(Mmax)}},
    {{"Mproton", ""},               {"", "", Mmax, 0, double(Mmax)}},
    {{"Mpionneg", ""},              {"", "", Mmax, 0, double(Mmax)}},
    {{"MgoodMid", ""},              {"", "", Mmax, 0, double(Mmax)}},
    {{"MprotonMid", ""},            {"", "", Mmax, 0, double(Mmax)}},
    {{"MpionnegMid", ""},           {"", "", Mmax, 0, double(Mmax)}},
    {{"psdE", ""},                  {"", "", int(psdEmax/10), 0, psdEmax}},
    {{"psd0E", ""},                 {"", "", int(psdEmax/10), 0, psdEmax}},
    {{"psd1E", ""},                 {"", "", int(psdEmax/10), 0, psdEmax}},
    {{"psd2E", ""},                 {"", "", int(psdEmax/10), 0, psdEmax}},
    {{"psd12E", ""},                {"", "", int(psdEmax/10), 0, psdEmax}},
    {{"trNhits", ""},               {"", "", 250, 0, 250}},
    {{"trNhitsVTPC", ""},           {"", "", 250, 0, 250}},
    {{"trNhitsCut", ""},            {"", "", 2, 0, 2}},
    {{"trNhitsToPot", ""},          {"", "", 100, 0, 2}},
    {{"trNhitsToPotCut", ""},       {"", "", 2, 0, 2}},
    {{"trDcaCut", ""},              {"", "", 2, 0, 2}},
    {{"trGood", ""},                {"", "", 2, 0, 2}},
    {{"trGoodNhits", ""},           {"", "", 2, 0, 2}},
    {{"vtxZ", ""},                  {"", "", nBinsVtx, -594, -590}},
    {{"trTofM2", ""},               {"", "", 100, -5, 5}},
    {{"trTofM2", "trGood"},         {"", "", 100, -5, 5}},
    {{"trTofM2", "pionneg"},        {"", "", 100, -5, 5}},
    {{"trTofM2", "proton"},         {"", "", 100, -5, 5}},
  };
  
  vector <pair <vector<string>, TH2DModel>> h2Models = {
    {{"adcS1", "adcS2", ""},              {"", "", 100, 100, 200, 120, 130, 250}},
    {{"vtxX", "bpd3x", ""},               {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
    {{"vtxY", "bpd3y", ""},               {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
    {{"bpd1x", "bpd1y", ""},              {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
    {{"bpd2x", "bpd2y", ""},              {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
    {{"bpd3x", "bpd3y", ""},              {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
    {{"vtxX", "vtxY", ""},                {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
    {{"vtxX", "Mgood", ""},               {"", "", nBinsVtx, -vtxMax, vtxMax, Mmax, 0, double(Mmax)}},
    {{"vtxY", "Mgood", ""},               {"", "", nBinsVtx, -vtxMax, vtxMax, Mmax, 0, double(Mmax)}},
    {{"vtxZ", "Mgood", ""},               {"", "", nBinsVtx, -594, -590, Mmax, 0, double(Mmax)}},
    {{"vtxChi2ndf", "Mgood", ""},         {"", "", 120, 0, 12, Mmax, 0, double(Mmax)}},
    {{"vtxXwrtBpd3", "vtxYwrtBpd3", ""},  {"", "", nBinsVtx, -vtxMax/10, vtxMax/10, nBinsVtx, -vtxMax/10, vtxMax/10}},
    {{"Mgood", "psdE", ""},               {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mgood", "psd0E", ""},              {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mgood", "psd1E", ""},              {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mgood", "psd2E", ""},              {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mgood", "psd12E", ""},             {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mgood", "psd3E", ""},              {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mgood", "centrality", ""},         {"", "", Mmax, 0, double(Mmax), 20, 0, 100}},
    {{"Mproton", "psdE", ""},             {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mproton", "psd0E", ""},            {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mproton", "psd1E", ""},            {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mproton", "psd2E", ""},            {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mproton", "psd12E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mproton", "psd3E", ""},            {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mproton", "centrality", ""},       {"", "", Mmax, 0, double(Mmax), 20, 0, 100}},
    {{"Mpionneg", "psdE", ""},            {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mpionneg", "psd0E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mpionneg", "psd1E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mpionneg", "psd2E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mpionneg", "psd12E", ""},          {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mpionneg", "psd3E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"Mpionneg", "centrality", ""},      {"", "", Mmax, 0, double(Mmax), 20, 0, 100}},
    {{"MgoodMid", "psdE", ""},            {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MgoodMid", "psd0E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MgoodMid", "psd1E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MgoodMid", "psd2E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MgoodMid", "psd12E", ""},          {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MgoodMid", "psd3E", ""},           {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MgoodMid", "centrality", ""},      {"", "", Mmax, 0, double(Mmax), 20, 0, 100}},
    {{"MprotonMid", "psdE", ""},          {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MprotonMid", "psd0E", ""},         {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MprotonMid", "psd1E", ""},         {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MprotonMid", "psd2E", ""},         {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MprotonMid", "psd12E", ""},        {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MprotonMid", "psd3E", ""},         {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MprotonMid", "centrality", ""},    {"", "", Mmax, 0, double(Mmax), 20, 0, 100}},
    {{"MpionnegMid", "psdE", ""},         {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MpionnegMid", "psd0E", ""},        {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MpionnegMid", "psd1E", ""},        {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MpionnegMid", "psd2E", ""},        {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MpionnegMid", "psd12E", ""},       {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MpionnegMid", "psd3E", ""},        {"", "", Mmax, 0, double(Mmax), int(psdEmax/10), 0, psdEmax}},
    {{"MpionnegMid", "centrality", ""},   {"", "", Mmax, 0, double(Mmax), 20, 0, 100}},
    {{"psd0E", "psd1E", ""},              {"", "", int(psdEmax/10), 0, psdEmax, int(psdEmax/10), 0, psdEmax}},
    {{"psd0E", "psd2E", ""},              {"", "", int(psdEmax/10), 0, psdEmax, int(psdEmax/10), 0, psdEmax}},
    {{"psd0E", "psd3E", ""},              {"", "", int(psdEmax/10), 0, psdEmax, int(psdEmax/10), 0, psdEmax}},
    {{"psd1E", "psd2E", ""},              {"", "", int(psdEmax/10), 0, psdEmax, int(psdEmax/10), 0, psdEmax}},
    {{"psd1E", "psd3E", ""},              {"", "", int(psdEmax/10), 0, psdEmax, int(psdEmax/10), 0, psdEmax}},
    {{"psd2E", "psd3E", ""},              {"", "", int(psdEmax/10), 0, psdEmax, int(psdEmax/10), 0, psdEmax}},
    {{"psdE", "centrality", ""},          {"", "", int(psdEmax/10), 0, psdEmax, 20, 0, 100}},
    {{"psd0E", "centrality", ""},         {"", "", int(psdEmax/10), 0, psdEmax, 20, 0, 100}},
    {{"psd1E", "centrality", ""},         {"", "", int(psdEmax/10), 0, psdEmax, 20, 0, 100}},
    {{"psd12E", "centrality", ""},        {"", "", int(psdEmax/10), 0, psdEmax, 20, 0, 100}},
    {{"psdModY", "psdModX", "psdModE"},   {"", "", 30, -60, 60, 30, -60, 60}},
    {{"psdModId", "psdModE", ""},         {"", "", 45, 1, 45, int(psdEmax/20), 0, 0.5*psdEmax}},
    {{"trDcaX", "trDcaY", ""},            {"", "", 100, -5, 5, 100, -5, 5}},
    {{"trDcaX", "trDcaY", "trGood"},      {"", "", 100, -5, 5, 100, -5, 5}},
    {{"trNhits", "trNhitsPot", ""},       {"", "", 250, 0, 250, 250, 0, 250}},
    {{"trNhits", "trNhitsPot", "trGood"}, {"", "", 250, 0, 250, 250, 0, 250}},
    {{"trEta", "trPt", ""},               {"", "", nBinsEta, 0, etaMax, nBinsPt, 0, ptMax}},
    {{"trEta", "trPt", "trGood"},         {"", "", nBinsEta, 0, etaMax, nBinsPt, 0, ptMax}},
    {{"trEta", "trPt", "trMid"},         {"", "", nBinsEta, 0, etaMax, nBinsPt, 0, ptMax}},
    {{"trEta", "trPt", "pionneg"},        {"", "", nBinsEta, 0, etaMax, nBinsPt, 0, ptMax}},
    {{"trEta", "trPt", "proton"},         {"", "", nBinsEta, 0, etaMax, nBinsPt, 0, ptMax}},
    {{"trPhi", "trPt", ""},               {"", "", nBinsPhi, -3.15, 3.15, nBinsPt, 0, ptMax}},
    {{"trPhi", "trPt", "trGood"},         {"", "", nBinsPhi, -3.15, 3.15, nBinsPt, 0, ptMax}},
    {{"trPhi", "trPt", "trMid"},         {"", "", nBinsPhi, -3.15, 3.15, nBinsPt, 0, ptMax}},
    {{"trPhi", "trPt", "pionneg"},        {"", "", nBinsPhi, -3.15, 3.15, nBinsPt, 0, ptMax}},
    {{"trPhi", "trPt", "proton"},         {"", "", nBinsPhi, -3.15, 3.15, nBinsPt, 0, ptMax}},
    {{"trPhi", "trEta", ""},              {"", "", nBinsPhi, -3.15, 3.15, nBinsEta, 0, etaMax}},
    {{"trPhi", "trEta", "trGood"},        {"", "", nBinsPhi, -3.15, 3.15, nBinsEta, 0, etaMax}},
    {{"trPhi", "trEta", "trMid"},        {"", "", nBinsPhi, -3.15, 3.15, nBinsEta, 0, etaMax}},
    {{"trPhi", "trEta", "pionneg"},       {"", "", nBinsPhi, -3.15, 3.15, nBinsEta, 0, etaMax}},
    {{"trPhi", "trEta", "proton"},        {"", "", nBinsPhi, -3.15, 3.15, nBinsEta, 0, etaMax}},
    {{"trY", "trPt", "pionneg"},          {"", "", nBinsY, yMin, yMax, nBinsPt, 0, ptMax}},
    {{"trY", "trPt", "proton"},           {"", "", nBinsY, yMin, yMax, nBinsPt, 0, ptMax}},
    {{"trPhi", "trY", "pionneg"},         {"", "", nBinsPhi, -3.15, 3.15, nBinsY, yMin, yMax}},
    {{"trPhi", "trY", "proton"},          {"", "", nBinsPhi, -3.15, 3.15, nBinsY, yMin, yMax}},
    {{"trQlog20p", "trdEdx", ""},         {"", "", 500, -10, 10, 200, 0, 4}},
    {{"trQlog20p", "trdEdx", "trGood"},   {"", "", 500, -10, 10, 200, 0, 4}},
    {{"trQlog20p", "trdEdx", "pionneg"},  {"", "", 500, -10, 10, 200, 0, 4}},
    {{"trQlog20p", "trdEdx", "proton"},   {"", "", 500, -10, 10, 200, 0, 4}},
//    {{"trdEdx", "trTofM2", ""},           {"", "", 200, 0, 4, 200, 0, 5}},
//    {{"trdEdx", "trTofM2", "trGood"},     {"", "", 200, 0, 4, 200, 0, 5}},
  };

  vector <pair <vector<string>, TProfile1DModel>> p1Models = {
    {{"vtxZ", "nSigmaVtxZ", ""},        {"", "", nBinsVtx, -594, -590}},
  };
  vector <pair <vector<string>, TProfile2DModel>> p2Models = {
    {{"vtxX", "vtxY", "nSigmaVtxXY", ""},     {"", "", nBinsVtx, -vtxMax, vtxMax, nBinsVtx, -vtxMax, vtxMax}},
  };
  saveHists(dd, h1Models,  outFile);
  saveHists(dd, p1Models,  outFile);
  saveHists(dd, h2Models,  outFile);
  saveHists(dd, p2Models,  outFile);
  outFile.Close();
}
